imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
                        - "form/fields.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    # db_driver other valid values are 'mongodb', 'couchdb' and 'propel'
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
         group_class: AppBundle\Entity\Group


assetic:
    debug:          '%kernel.debug%'
   # use_controller: '%kernel.debug%'
    use_controller: true
    filters:
        cssrewrite: ~
    assets:
        # An array of named assets (e.g. some_asset, some_other_asset)
        uikit_js:
            inputs:               ['assets/vendor/jquery/dist/jquery.js','assets/vendor/uikit/js/uikit.js']
            filters:              []
            options:
                # A key-value array of options and values
                some_option_name: []
        uikit_css:
            inputs:               ['assets/vendor/uikit/css/uikit.css','assets/vendor/uikit/css/custom.css']
            filters:              []
            options:
                # A key-value array of options and values
                some_option_name: []
        gdsk_css:
            inputs:               ['assets/vendor/gdsk/bootstrap3/css/bootstrap.css','assets/vendor/gdsk/assets/css/get-shit-done.css','assets/vendor/gdsk/assets/css/demo.css','assets/vendor/gdsk/bootstrap3/css/font-awesome.css','assets/vendor/gdsk/assets/css/custom.css']
            filters:              []
            options:
                # A key-value array of options and values
                some_option_name: []

        gdsk_js:
                    inputs:               ['assets/vendor/gdsk/jquery/jquery-1.10.2.js','assets/vendor/gdsk/assets/js/jquery-ui-1.10.4.custom.min.js','assets/vendor/gdsk/bootstrap3/js/bootstrap.js','assets/vendor/gdsk/assets/js/gsdk-checkbox.js','assets/vendor/gdsk/assets/js/gsdk-radio.js','assets/vendor/gdsk/assets/js/gsdk-bootstrapswitch.js','assets/vendor/gdsk/assets/js/get-shit-done.js','assets/vendor/gdsk/assets/js/custom.js']
                    filters:              []
                    options:
                        # A key-value array of options and values
                        some_option_name: []


doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

